src/main/java/au/usyd/elec3609/domain/Item.java
package au.usyd.elec3609.domain;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * Item Class is a Plain Old Java Object which contains
 * all the database attributes. 
 * 
 * It contains all item table attributes the getters and the setters which will be used in the
 * view and also in the service to interact with the database. 
 */

@Entity
@Table(name = "Item")
public class Item implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	@Column(name = "Id")
	private long id;

	@Column(name = "ItemName")
	private String itemname;

	@Column(name = "Category")
	private String category;

	@Column(name = "ItemDescription")
	private String itemdescription;

	@Column(name = "QuantityAvailable")
	private int quantityavailable;

	@Column(name = "TotalQuantity")
	private int totalquantity;

	@Column(name = "RentalPrice")
	private double rentalprice;

	@Column(name = "PurchasePrice")
	private double purchaseprice;

	@Column(name = "ImageFilePath")
	private String imageFilePath;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getItemName() {
		return itemname;
	}

	public void setItemName(String itemname) {
		this.itemname = itemname;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getItemDescription() {
		return itemdescription;
	}

	public void setItemDescription(String itemdescription) {
		this.itemdescription = itemdescription;
	}

	public int getQuantityAvailable() {
		return quantityavailable;
	}

	public void setQuantityAvailable(int quantityavailable) {
		this.quantityavailable = quantityavailable;
	}

	public int getTotalQuantity() {
		return totalquantity;
	}

	public void setTotalQuantity(int totalquantity) {
		this.totalquantity = totalquantity;
	}

	public double getRentalPrice() {
		return rentalprice;
	}

	public void setRentalPrice(double rentalprice) {
		this.rentalprice = rentalprice;
	}

	public double getPurchasePrice() {
		return rentalprice;
	}

	public void setPurchasePrice(double purchaseprice) {
		this.purchaseprice = purchaseprice;
	}

	public String getImageFilePath() {
		return imageFilePath;
	}

	public void setImageFilePath(String imageFilePath) {
		this.imageFilePath = imageFilePath;
	}

}

src/main/java/au/usyd/elec3609/web/CheckoutController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec3609.service.UserManager;

@Controller
public class CheckoutController {
	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	@Resource(name = "userManager")
	private UserManager userManger;

	/**
	 * Show dashboard page
	 */
	@RequestMapping(value = "/checkout", method = RequestMethod.GET)
	public String dashboard(Locale locale, Model model,
			HttpServletRequest session) {
		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG,
				DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("item",
				session.getSession().getAttribute("ListOfItems"));

		return "checkout";
	}

	@RequestMapping(value = "/checkout", method = RequestMethod.POST)
	public String dashboard(Locale locale, Model model) {
		return "checkout";
	}

}

src/main/java/au/usyd/elec3609/web/DashboardController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec3609.domain.User;
import au.usyd.elec3609.service.UserManager;

@Controller
public class DashboardController {
	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	@Resource(name = "userManager")
	private UserManager userManger;

	/**
	 * Show dashboard page
	 */
	@RequestMapping(value = "/dashboard", method = RequestMethod.GET)
	public String dashboard(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG,
				DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("serverTime", formattedDate);

		return "dashboard";
	}

}

src/main/java/au/usyd/elec3609/web/HomeController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec3609.domain.Item;
import au.usyd.elec3609.service.ItemManager;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	@Resource(name = "itemManager")
	public ItemManager itemManager;

	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/home", method = RequestMethod.GET)
	public String home(Locale locale, Model model,
			HttpServletRequest httpServletRequest) {
		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG,
				DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("serverTime", formattedDate);

		model.addAttribute("item", itemManager.getItems());
		HttpSession session = httpServletRequest.getSession();
		session.setAttribute("Authentication", "false");
		session.setAttribute("AttemptedLogin", "false");
		List<Item> itemList = new ArrayList<Item>();
		session.setAttribute("ListOfItems", itemList);
		return "home";
	}

}

src/main/java/au/usyd/elec3609/web/LoginController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec3609.service.UserManager;

@Controller
public class LoginController {

	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	@Resource(name = "userManager")
	UserManager userManager;

	/**
	 * Simply selects the login view
	 */
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String login(Locale locale, Model model,
			HttpServletRequest httpServletRequest) {

		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG,
				DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		HttpSession session = httpServletRequest.getSession();
		if (session.getAttribute("Authentication").equals("false")) {
			if (session.getAttribute("AttemptedLogin").equals("true")) {
				model.addAttribute("authenticationMessage",
						"Authentication failed");

			}

			model.addAttribute("authenticationMessage", "");

		}

		else {
			model.addAttribute("authenticationMessage", "You are logged in");

		}

		return "login";
	}

	/**
	 * Very basic verification of login username and password
	 */
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String verifyLogin(HttpServletRequest httpServletRequest, Model model) {
		HttpSession session = httpServletRequest.getSession();

		if (userManager.login(httpServletRequest.getParameter("username"),
				httpServletRequest.getParameter("password"))) {
			session.setAttribute("Authentication", "true");
			return "redirect:/dashboard";
		}

		else {
			session.removeAttribute("AttemptedLogin");
			session.setAttribute("AttemptedLogin", "true");
			model.addAttribute("authenticationMessage", "Authentication failed");
			return "login";
		}

	}

}

src/main/java/au/usyd/elec3609/web/RegisterController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

import au.usyd.elec3609.domain.Item;
import au.usyd.elec3609.domain.User;
import au.usyd.elec3609.service.ItemManager;
import au.usyd.elec3609.service.UserManager;

@Controller
@SessionAttributes("User")
public class RegisterController {

	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	@Resource(name = "userManager")
	UserManager userManager;

	@Resource(name = "itemManager")
	ItemManager itemManager;

	/**
	 * Show Register page
	 */
	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String register(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);

		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG,
				DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("serverTime", formattedDate);
		return "register";
	}

	/**
	 * User has sent information for registration
	 */
	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String submitRegistration(HttpServletRequest httpServletRequest) {

		User user = new User();
		userManager.register(user, httpServletRequest.getParameter("username"),
				httpServletRequest.getParameter("password"),
				httpServletRequest.getParameter("firstname"),
				httpServletRequest.getParameter("lastname"),
				httpServletRequest.getParameter("sex"),
				httpServletRequest.getParameter("dateofbirth"),
				httpServletRequest.getParameter("emailaddress"));

		HttpSession session = httpServletRequest.getSession();
		session.setAttribute("User", user);

		Item item1 = new Item();
		item1.setItemName("iPhone 5 Charger");
		item1.setCategory("Phone Chargers");
		item1.setItemDescription("Charger for Apple iPhone");
		item1.setQuantityAvailable(10);
		item1.setTotalQuantity(25);
		item1.setRentalPrice(2);
		item1.setImageFilePath("/src/main/webapp/resources/images/charger.jpg");
		itemManager.addItem(item1);

		Item item2 = new Item();
		item2.setItemName("Software Engineering for Internet Applications");
		item2.setCategory("Books");
		item2.setItemDescription("A reference guide for software engineering students and also those pursuing courses on internet application and other related courses. This book is paperback version and is recommended by both professionals and also lecturers.");
		item2.setQuantityAvailable(1);
		item2.setTotalQuantity(1);
		item2.setRentalPrice(0.125);
		item2.setPurchasePrice(50);
		item2.setImageFilePath("/src/main/webapp/resources/images/book.jpg");
		itemManager.addItem(item2);

		Item item3 = new Item();
		item3.setItemName("Laboratory Goggles");
		item3.setCategory("Electronic Equipment");
		item3.setItemDescription("A pair of plastic lab goggles. Highly durable and of the best quality");
		item3.setQuantityAvailable(5);
		item3.setTotalQuantity(5);
		item3.setRentalPrice(2.50);
		item3.setImageFilePath("/src/main/webapp/resources/images/goggles.jpg");
		itemManager.addItem(item3);

		Item item4 = new Item();
		item4.setItemName("Calculator");
		item4.setCategory("Before Exam");
		item4.setItemDescription("CASIO 82AU (Recommended scientific calculator for all university quizzes and exams) ");
		item4.setQuantityAvailable(1);
		item4.setTotalQuantity(3);
		item4.setRentalPrice(1);
		item4.setImageFilePath("/src/main/webapp/resources/images/calculator.png");
		itemManager.addItem(item4);

		Item item5 = new Item();
		item5.setItemName("Arduino");
		item5.setCategory("Electronic Equipment");
		item5.setItemDescription("Circuit Board");
		item5.setQuantityAvailable(5);
		item5.setTotalQuantity(5);
		item5.setRentalPrice(2.50);
		// item5.setImageFilePath();
		itemManager.addItem(item5);

		return "redirect:/login.htm";
	}
}

src/main/java/au/usyd/elec3609/web/SearchController.java
package au.usyd.elec3609.web;

import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import au.usyd.elec3609.domain.Item;
import au.usyd.elec3609.service.ItemManager;

@Controller
public class SearchController {

	private static final Logger logger = LoggerFactory
			.getLogger(SearchController.class);

	@Resource(name = "itemManager")
	private ItemManager itemManager;

	/**
	 * Simply selects the search view to render by returning its name.
	 */
	@RequestMapping(value = "/search", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {

		model.addAttribute("listItem", itemManager.getItems());

		// model.addAttribute("Item", new Item());

		return "search";
	}

	@RequestMapping(value = "/complete", method = RequestMethod.GET)
	public @ResponseBody List<Item> autocomplete(
			@RequestParam(value = "itemName") String data, Model model) {
		return itemManager.getItemsByPartialName(data);

	}

	@RequestMapping(value = "/search", method = RequestMethod.POST)
	public String redirectToItem(@RequestParam("myItem") String itemName,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();

		session.setAttribute("itemName", itemName);

		return "redirect:/searchItem";
	}

}

src/main/java/au/usyd/elec3609/web/ViewItemController.java
package au.usyd.elec3609.web;

import java.util.List;
import java.util.Locale;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import au.usyd.elec3609.domain.Item;
import au.usyd.elec3609.service.ItemManager;

@Controller
public class ViewItemController {
	private static final Logger logger = LoggerFactory
			.getLogger(HomeController.class);

	@Resource(name = "itemManager")
	private ItemManager itemManager;

	/**
	 * Show viewItem page
	 */

	@RequestMapping(value = "/viewItem", method = RequestMethod.GET)
	public String dashboard(Locale locale, Model model,
			HttpServletRequest httpServletRequest) {

		HttpSession session = httpServletRequest.getSession();

		String itemCategory = (String) session.getAttribute("categoryToVisit");

		model.addAttribute("item",
				itemManager.getItemsByCategories(itemCategory));
		return "viewItem";
	}

	@RequestMapping(value = "/viewItem", method = RequestMethod.POST)
	public String addToCart(HttpServletRequest httpServletRequest, Model model) {
		System.out.println(httpServletRequest.getParameter("item"));
		Long itemId = Long.valueOf(httpServletRequest.getParameter("item"))
				.longValue();

		Item item = itemManager.getItemsById(itemId);
		// item = (Item) itemObject;
		List<Item> tempList;
		HttpSession session = httpServletRequest.getSession();

		tempList = (List<Item>) session.getAttribute("ListOfItems");
		session.removeAttribute("ListOfItems");
		tempList.add(item);
		session.setAttribute("ListOfItems", tempList);
		if (item.getQuantityAvailable() > 0) {
			item.setQuantityAvailable(item.getQuantityAvailable() - 1);
			return "redirect:/checkout";
		}

		else {
			model.addAttribute("message", "Out of Stock");
			return "redirect:/viewItem";
		}

	}
}

src/main/webapp/WEB-INF/views/categories.jsp
<%@ page import="java.io.*,java.util.*"%>
<%@ page session="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar" aria-expanded="false"
				aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<c:url value="/home" />">Hyra</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="<c:url value="/register" />">Register</a></li>
				<li><a href="<c:url value="/login" />">Login</a></li>
				<li><a href="<c:url value="/search" />">Search</a></li>
				<li class="active"><a href="<c:url value="/categories" />">View
						Categories</a></li>
				<li><a href="<c:url value="/checkout" />">View Checkout
						Cart</a></li>			
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>

<div class="container">
<h1>Categories</h1>
<br />
<br />
<form action="categories" method="post">
	<input type="submit" value="Books" name="Books"></input> 
	<br />
	<br />
	<input type="submit" value="Phone Chargers" name="Phone Chargers"></input>
	<br />
	<br /> 
	<input type="submit" value="Laptop Chargers" name="Laptop Chargers"></input>
	<br />
	<br />
	<input type="submit" value="Before Exam" name="Before Exam"></input>
	<br />
	<br /> 
	<input type="submit" value="Electronic Equipment" name="Electronic Equipment"></input>		
</form>
</div>
</html>

src/main/webapp/WEB-INF/views/checkout.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<head>
<title>Checkout</title>
</head>
<body>

	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar" aria-expanded="false"
					aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<c:url value="/home" />">Hyra</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="<c:url value="/register" />">Register</a></li>
					<li><a href="<c:url value="/login" />">Login</a></li>
					<li><a href="<c:url value="/search" />">Search</a></li>
					<li><a href="<c:url value="/categories" />">View
							Categories</a></li>
					<li class="active"><a href="<c:url value="/checkout" />">View
							Checkout Cart</a></li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container">
		<c:if test="${item.size() == 0}">
			<p>No Items are in this Category</p>
		</c:if>
		<c:forEach items="${item}" var="item">
			<i>Name: <c:out value="${item.itemName}" /></i>
			<br />
			<i>Description: <c:out value="${item.itemDescription}" /></i>
			<br />
			<i>Rental price: <c:out value="${item.rentalPrice}" /></i>
			<br />
			<br />
			<form action="checkout" method="post" name=confirm>
				<button type="Submit" name="item" value="${item.id}">Confirm Payment</button>
			</form>
			<br />
		</c:forEach>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/dashboard.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>

<html>
<body>

	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar" aria-expanded="false"
					aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<c:url value="/home" />">Hyra</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="<c:url value="/register" />">Register</a></li>
					<li><a href="<c:url value="/login" />">Login</a></li>
					<li><a href="<c:url value="/search" />">Search</a></li>
					<li><a href="<c:url value="/categories" />">View
							Categories</a></li>
					<li><a href="<c:url value="/checkout" />">View Checkout
							Cart</a></li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>


	<div class="container">

		<h1>Dashboard</h1>

		<p>Welcome to your Dashboard. From here you can view the
			Categories, Search for an item and view your checkout cart.</p>

		<br />


		<div class="list-group">
			<a href="categories.htm" class="list-group-item">View Categories</a>
			<a href="search.htm" class="list-group-item">Search</a> <a
				href="checkout.htm" class="list-group-item">Checkout Cart</a>
		</div>

	</div>

</body>

</html>

src/main/webapp/WEB-INF/views/viewItem.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<body>

	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar" aria-expanded="false"
					aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<c:url value="/home" />">Hyra</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="<c:url value="/register" />">Register</a></li>
					<li><a href="<c:url value="/login" />">Login</a></li>
					<li><a href="<c:url value="/search" />">Search</a></li>
					<li><a href="<c:url value="/categories" />">View
							Categories</a></li>
					<li><a href="<c:url value="/checkout" />">View Checkout
							Cart</a></li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container">
		<h1>Items</h1>
		<c:if test="${item.size() == 0}">
			<p>No Items are in this Category</p>
		</c:if>
		<c:forEach items="${item}" var="item">
			<i>Name: <c:out value="${item.itemName}" /></i>
			<br />
			<i>Description: <c:out value="${item.itemDescription}" /></i>
			<br />
			<i>Quantity Available: <c:out value="${item.quantityAvailable}" /></i>
			<br />
			<i>Total Quantity: <c:out value="${item.totalQuantity}" /></i>
			<br />
			<i>Rental price: <c:out value="${item.rentalPrice}" /></i>
			<br />
			<br />
			
			<!-- <img src="${item.imageFilePath}"></img>-->
			
			<form action="viewItem.htm" method="post" name=addToCart>
				<button type="Submit" name="item" value="${item.id}">Add to
					Cart</button>
			</form>
			<br />
		</c:forEach>
		<p></p>
		${message}
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/viewItemFromSearch.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<html>
<body>

<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<c:url value="/home" />">Hyra</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<c:url value="/register" />">Register</a></li>
            <li><a href="<c:url value="/login" />">Login</a></li>
            <li><a href="<c:url value="/search" />">Search</a></li>
            <li><a href="<c:url value="/categories" />">View Categories</a></li>
            <li><a href="<c:url value="/checkout" />">View Checkout Cart</a></li>            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

	<p></p>
	<div class="container">
	<h3>Items</h3>
	<c:if test="${item.size()== 0}">
		<p>No Items are in this Category</p>
	</c:if>
	<c:forEach var="item" items="${item}">
		
		<i>Name: <c:out value="${item.itemName}" /></i><br/>
		<i>Description: <c:out value="${item.itemDescription}" /></i><br/>
		<i>Quantity Available: <c:out value="${item.quantityAvailable}" /></i><br/>
		<i>Total Quantity: <c:out value="${item.totalQuantity}" /></i><br/>
		<i>Rental price: <c:out value="${item.rentalPrice}" /></i><br/>
		<i>Purchase price: <c:out value="${item.purchasePrice}" /></i>
		<br></br>
		
	</c:forEach>
	</div>
	<p></p>

</body>
</html>